Repository MentorsWithoutBorders/mwb-partners-admin, pull requests merged in 2023-09, with the labels that each got.

#75 14 login page
  .env.example
  .prettierignore
  package-lock.json
  package.json
  src/components/Form/SignIn/SignInForm.styled.ts
  src/components/Form/SignIn/SignInForm.tsx
  src/components/Form/SignUp/SignUpForm.styled.ts
  src/components/Form/SignUp/SignUpForm.tsx
  src/components/LoadingPage/LoadingPage.styled.ts
  src/components/LoadingPage/LoadingPage.tsx
  src/components/Logout/Logout.tsx
  src/config/backend/backend-api-routes.ts
  src/config/frontend/frontend-routes.ts
  src/containers/AuthGuard/AuthGuard.tsx
  src/containers/dashboard/DashboardLayout.tsx
  src/lib/api-client.ts
  src/lib/auth/auth-client.ts
  src/lib/fetcher/fetcher.ts
  src/pages/_app.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/app/index.tsx
  src/pages/app/mentors.tsx
  src/pages/app/students.tsx
  src/pages/index.tsx
  src/types/with-authentication/with-authentication.type.ts
  types/next-auth.d.ts
Labels: Priority: High

#76 Issue #54 - Centres dropdown on Students table
  .env.example
  src/components/CentresDropdown/CentresDropdown.styled.ts
  src/components/CentresDropdown/CentresDropdown.tsx
  src/components/TestimonialPopup/TestimonialPopup.styled.ts
  src/components/TestimonialPopup/TestimonialPopup.tsx
  src/lib/centres/centres-client.ts
  src/pages/app/students.tsx
  src/styles/pages/app/students.styled.ts
  src/types/centre.type.ts
Labels: ready for review

#78 feat: add mentors stats
  .env.example
  package-lock.json
  package.json
  src/components/DashboardItem/DashboardItem.styled.ts
  src/components/DashboardItem/DashboardItem.tsx
  src/components/Table/DataModal/DataModal.styled.ts
  src/components/Table/DataModal/DataModal.tsx
  src/components/Table/DataTable/DataTable.styled.ts
  src/components/Table/DataTable/DataTable.tsx
  src/components/Table/FilterButton/FilterButton.styled.ts
  src/components/Table/FilterButton/FilterOutlinedInput.styled.ts
  src/components/Table/FilterButton/SearchFilterField.tsx
  src/components/Table/StudentsTable/StudentsTable.styled.ts
  src/components/Table/StudentsTable/StudentsTable.tsx
  src/components/Table/interfaces.ts
  src/components/table/DataTable/DataTable.tsx
  src/lib/fetcher/fetcher.ts
  src/lib/hooks/useDebounce.ts
  src/lib/mentors/mentors-client.ts
  src/pages/_app.tsx
  src/pages/app/mentors.tsx
  src/pages/app/students.tsx
  src/pages/index.tsx
  src/styles/globals.css
  src/styles/theme.ts
  src/types/mentors/stats.type.ts
Labels: frontend

#82 feat: integrate APIs in mentors and students pages #81
  package-lock.json
  package.json
  src/api/mentors.ts
  src/components/CentresDropdown/CentresDropdown.tsx
  src/components/Layout/Layout.tsx
  src/components/Table/DataTable/DataTable.styled.ts
  src/components/Table/DataTable/DataTable.tsx
  src/components/Table/StudentsTable/StudentsTable.styled.ts
  src/components/Table/StudentsTable/StudentsTable.tsx
  src/containers/MentorsTable/MentorsTable.tsx
  src/lib/centres/centres-client.ts
  src/lib/mentors/mentors-client.ts
  src/lib/students/students-client.ts
  src/pages/app/mentors.tsx
  src/pages/app/students.tsx
  src/styles/theme.ts
  src/types/mentors/mentor.type.ts
  src/types/students/stats.type.ts
  src/types/students/student.type.ts
  src/types/students/table-types.ts
Labels: frontend

#83 feat: add 'view mode' toggle to Dashboard screen (issue #45)
  src/pages/app/index.tsx
  src/styles/pages/app/index.styled.ts
Labels: ready for review
